language: csharp
sudo: required
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
os:
  - linux
install:
  - export PATH="$PATH:$HOME/nginxinstall/sbin/"
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl http://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
before_script:
  - npm install -g bower
  - npm install -g gulp
branches:
  only:
    - master
    - /^(.*\/)?ci-.*$/
script:
  - ./build.sh
